// <auto-generated />
using System;
using AdminService.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminService.DAL.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminService.DAL.Entities.ClientData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("clientsdata", null, t =>
                        {
                            t.HasCheckConstraint("age", "age > 18");
                        });
                });

            modelBuilder.Entity("AdminService.DAL.Entities.ClientOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientDataId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ClientId");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("sumPay")
                        .HasColumnType("real");

                    b.Property<int>("timeStudy")
                        .HasColumnType("int");

                    b.Property<string>("typeEngeeniring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("clientDataId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientOrder_ClientDataId");

                    b.ToTable("clientorders", (string)null);
                });

            modelBuilder.Entity("AdminService.DAL.Entities.ClientOrder", b =>
                {
                    b.HasOne("AdminService.DAL.Entities.ClientData", "clientData")
                        .WithOne("clientOrder")
                        .HasForeignKey("AdminService.DAL.Entities.ClientOrder", "clientDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clientData");
                });

            modelBuilder.Entity("AdminService.DAL.Entities.ClientData", b =>
                {
                    b.Navigation("clientOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
